services:
  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_DATABASE
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8080:80
      - 8081:443
    depends_on:
      - postgres
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target

volumes:
  postgres-data:
  cargo-cache:
  target-cache:
